"""mDNS / Bonjour announcements.

Two mechanisms, both optional:

* An Avahi static service file is written to ``/etc/avahi/services`` when that
  directory exists.  This is the most reliable option on Raspberry Pi OS and
  Debian and survives daemon restarts.
* If the ``zeroconf`` Python module is installed, the services are registered
  directly as well, which also works on hosts without Avahi.

Announced services:
  ``_pdl-datastream._tcp`` (port 9100)  - RAW printing, what POS apps look for
  ``_http._tcp``           (web port)   - the BonBridge web interface

References
----------
* RFC 6762 (Multicast DNS)     https://datatracker.ietf.org/doc/html/rfc6762
* RFC 6763 (DNS-SD)            https://datatracker.ietf.org/doc/html/rfc6763
* Avahi static service files   https://www.avahi.org/
* python-zeroconf (optional)   https://github.com/python-zeroconf/python-zeroconf
* Full reference list: docs/en/09-references.md / docs/de/09-referenzen.md
"""

from __future__ import annotations

import logging
import socket
from pathlib import Path
from typing import Any, Dict, List, Optional
from xml.sax.saxutils import escape

log = logging.getLogger(__name__)

AVAHI_SERVICE_DIR = Path("/etc/avahi/services")
AVAHI_SERVICE_FILE = AVAHI_SERVICE_DIR / "bonbridge.service"

try:  # pragma: no cover
    from zeroconf import ServiceInfo, Zeroconf

    HAVE_ZEROCONF = True
except Exception:  # noqa: BLE001
    ServiceInfo = None  # type: ignore[assignment]
    Zeroconf = None  # type: ignore[assignment]
    HAVE_ZEROCONF = False


def write_avahi_service_file(
    printers: List[Dict[str, Any]], web_port: int, hostname_label: str = ""
) -> Optional[Path]:
    """Write a static Avahi service definition.  Returns the path or ``None``."""
    if not AVAHI_SERVICE_DIR.is_dir():
        return None
    label = hostname_label or socket.gethostname()
    lines = [
        '<?xml version="1.0" standalone="no"?>',
        '<!DOCTYPE service-group SYSTEM "avahi-service.dtd">',
        "<!-- generated by BonBridge, do not edit -->",
        "<service-group>",
        f"  <name replace-wildcards=\"yes\">BonBridge on %h</name>",
        "  <service>",
        "    <type>_http._tcp</type>",
        f"    <port>{int(web_port)}</port>",
        "    <txt-record>path=/</txt-record>",
        "  </service>",
    ]
    for printer in printers:
        name = escape(str(printer.get("name") or printer.get("id") or "printer"))
        port = int(printer.get("port") or 9100)
        lines += [
            "  <service>",
            "    <type>_pdl-datastream._tcp</type>",
            f"    <port>{port}</port>",
            f"    <txt-record>ty={name}</txt-record>",
            "    <txt-record>pdl=application/octet-stream</txt-record>",
            f"    <txt-record>note={escape(label)}</txt-record>",
            "  </service>",
        ]
    lines.append("</service-group>")
    try:
        AVAHI_SERVICE_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
        log.info("Avahi service file written: %s", AVAHI_SERVICE_FILE)
        return AVAHI_SERVICE_FILE
    except OSError as exc:
        log.warning("Cannot write %s: %s", AVAHI_SERVICE_FILE, exc)
        return None


class MdnsAdvertiser:
    """Optional in-process mDNS registration via python-zeroconf."""

    def __init__(self) -> None:
        self._zeroconf: Any = None
        self._services: List[Any] = []

    @property
    def active(self) -> bool:
        return self._zeroconf is not None

    def start(self, printers: List[Dict[str, Any]], web_port: int) -> None:
        if not HAVE_ZEROCONF:
            return
        try:
            self._zeroconf = Zeroconf()
        except Exception as exc:  # noqa: BLE001
            log.warning("zeroconf unavailable: %s", exc)
            self._zeroconf = None
            return

        host = socket.gethostname().split(".")[0]
        try:
            address = socket.inet_aton(_primary_ip())
        except OSError:
            address = None

        entries = [
            (
                "_http._tcp.local.",
                f"BonBridge-{host}._http._tcp.local.",
                int(web_port),
                {"path": "/"},
            )
        ]
        for printer in printers:
            entries.append(
                (
                    "_pdl-datastream._tcp.local.",
                    f"{printer.get('id', 'printer')}-{host}._pdl-datastream._tcp.local.",
                    int(printer.get("port") or 9100),
                    {"ty": str(printer.get("name") or ""), "pdl": "application/octet-stream"},
                )
            )

        for service_type, name, port, properties in entries:
            try:
                info = ServiceInfo(
                    service_type,
                    name,
                    addresses=[address] if address else [],
                    port=port,
                    properties=properties,
                    server=f"{host}.local.",
                )
                self._zeroconf.register_service(info)
                self._services.append(info)
            except Exception as exc:  # noqa: BLE001
                log.debug("Cannot register %s: %s", name, exc)
        if self._services:
            log.info("mDNS: %s service(s) registered via zeroconf", len(self._services))

    def stop(self) -> None:
        if self._zeroconf is None:
            return
        for info in self._services:
            try:
                self._zeroconf.unregister_service(info)
            except Exception:  # noqa: BLE001
                pass
        try:
            self._zeroconf.close()
        except Exception:  # noqa: BLE001
            pass
        self._zeroconf = None
        self._services = []


def _primary_ip() -> str:
    from .sysinfo import primary_ipv4

    return primary_ipv4()
